const COLOR_BLACK = '#000000';
const COLOR_WHITE ='#FFFFFF';
const COLOR_PRIMARY = '#E83F5B';
const COLOR_SECONDARY = '#80BCB8';
const COLOR_LIGHT = '#F9F9F9';
const COLOR_LIGHTINPUTBG = '#EFEFEF';
const COLOR_LIGHTTEXT = '#C0C0C0';

const FONT_SMALLER = '14px';
const FONT_SMALL = '16px';
const FONT_REGULAR = '18px';
const FONT_MEDIUM = '20px';
const FONT_BIG = '24px';
const FONT_BIGGER = '28px';
const FONT_BIGGEST = '30px';
const FONT_LOW_HEADER = '32px';
const FONT_MEDIUM_HEADER = '36px';
const FONT_HIGH_HEADER = '64px';

export {
  COLOR_BLACK,
  COLOR_LIGHT,
  COLOR_LIGHTINPUTBG,
  COLOR_LIGHTTEXT,
  COLOR_PRIMARY,
  COLOR_SECONDARY,
  COLOR_WHITE,
  FONT_BIG,
  FONT_BIGGER,
  FONT_BIGGEST,
  FONT_SMALL,
  FONT_SMALLER,
  FONT_REGULAR,
  FONT_MEDIUM,
  FONT_LOW_HEADER,
  FONT_MEDIUM_HEADER,
  FONT_HIGH_HEADER
};